name: check-build

on:
  pull_request:

jobs:
  # Temporär deaktiviert - Build läuft nur auf main branch
  # create-docker-image:
  #   runs-on: ubuntu-latest
  #   name: Check PR - Build
  #   concurrency:
  #     group: ${{ github.event.pull_request.number }}-check-pr
  #     cancel-in-progress: true
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v4
  #     - uses: pnpm/action-setup@v4
  #     - name: Set up Docker Buildx
  #       uses: docker/setup-buildx-action@v3
  #     - name: Build
  #       uses: docker/build-push-action@v6
  #       with:
  #         push: false
  
  # Einfacher Check, dass die Syntax stimmt
  lint-check:
    runs-on: ubuntu-latest
    name: Check PR - Lint
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Run linter
        run: pnpm lint